name: generate pacman animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github-contribution-grid-pacman.svg
        uses: <seu-repo-com-pacman-action>@v1
        with:
          github_user_name: nairan660
          outputs: |
            dist/github-contribution-grid-pacman.svg
            dist/github-contribution-grid-pacman-dark.svg?palette=github-dark

      - name: push github-contribution-grid-pacman.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
